# This is to be used if the app is being deployed in google app engine, GCP
runtime: nodejs
env: flex
# service: generic-pond-services

manual_scaling:
  instances: 1

beta_settings:
  # The connection name of your instance, available by using
  # 'gcloud beta sql instances describe [INSTANCE_NAME]' or from
  # the Instance details page in the Google Cloud Platform Console.
  cloud_sql_instances: generic-services:asia-south1:services-database

# includes:
#   - secret.yaml
